USE master
CREATE DATABASE CM_CAL
ON
( NAME = CM_CAL_1, FILENAME = 'E:\SQL_Database\CM_CAL_1.mdf', SIZE = 5620, MAXSIZE = Unlimited, FILEGROWTH = 1855)
LOG ON
( NAME = CAL_log, FILENAME = 'G:\SQL_Logs\CM_CAL.ldf', SIZE = 1855, MAXSIZE = 1855, FILEGROWTH = 512)
ALTER DATABASE CM_CAL
ADD FILE (NAME = CM_CAL_2, FILENAME = 'E:\SQL_Database\CM_CAL_2.mdf', SIZE = 5620, MAXSIZE = Unlimited, FILEGROWTH = 1855)